#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.murphydot/home/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.murphydot/home/.zprezto/init.zsh"
fi

# Customize to your needs...
alias ed=vim
alias nisd="npm install --save-dev"
alias nusd="npm uninstall --save-dev"
alias nis="npm install --save"
alias nus="npm uninstall --save"

# Base 16 Colors
#BASE16_SHELL="$HOME/.config/base16-shell/base16-eighties.dark.sh"
#[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL
 
function erc() {
  ed ~/.zshrc
}

function rrc() {
  source ~/.zshrc
}

function kata() {
  sm_go_env
  cd $HOME/projects/katamari/$@
}

function mkbin() {
  touch $HOME/bin/$1
  chmod a+x $HOME/bin/$1
  ed $HOME/bin/$1
}

function gulplist() {
  cat gulpfile.* | grep .task
}

export KATAMARI="/Users/murphy/SM/katamari"
export PROJECTS=$HOME/projects

export PATH="/Users/murphy/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export PATH="/usr/local/go/bin:$PATH"

# export DOCKER_HOST=tcp://192.168.59.103:2376
# export DOCKER_CERT_PATH=/Users/murphy/.boot2docker/certs/boot2docker-vm
# export DOCKER_TLS_VERIFY=1
# 
export VAGRANT_CWD=$HOME/VMs/smnet
# 
export NVM_DIR="/Users/murphy/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
export KARMA_DIR=~/.nvm/`cat ~/.nvm/alias/default`/lib/node_modules/karma/bin
export PATH=$KARMA_DIR:$PATH
export GOPATH=$HOME/projects/katamari/go
export PATH=$PATH:/usr/local/go/bin
# eval "$(rbenv init -)"
alias rm=trash

# Add GHC 7.8.3 to the PATH, via http://ghcformacosx.github.io/
export GHC_DOT_APP="/Applications/ghc-7.8.3.app"
if [ -d "$GHC_DOT_APP" ]; then
    export PATH="${HOME}/.cabal/bin:${GHC_DOT_APP}/Contents/bin:${PATH}"
fi

