#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.murphydot/home/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.murphydot/home/.zprezto/init.zsh"
fi

# Customize to your needs...
alias ed=vim
alias nisd="npm install --save-dev"
alias nusd="npm uninstall --save-dev"
alias nis="npm install --save"
alias nus="npm uninstall --save"

# Base 16 Colors
#BASE16_SHELL="$HOME/.config/base16-shell/base16-eighties.dark.sh"
#[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL
 
function erc() {
  ed ~/.zshrc
}

function rrc() {
  source ~/.zshrc
}

export PROJECTS=$HOME/projects

export PATH="$HOME/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export VAGRANT_CWD=$HOME/vagrant/kuali

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm


## The following section only runs on Mac computers:
if [[ "$OSTYPE" == "darwin"* ]]; then

  alias rm=trash

  # Add GHC 7.8.3 to the PATH, via http://ghcformacosx.github.io/
  export GHC_DOT_APP="/Applications/ghc-7.8.3.app"
  if [ -d "$GHC_DOT_APP" ]; then
      export PATH="${HOME}/.cabal/bin:${GHC_DOT_APP}/Contents/bin:${PATH}"
  fi

fi
